<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-10-18 10:40
=======
# Generated by Django 4.1.2 on 2022-10-18 10:58
>>>>>>> 9ed58853aef5197b880d5c1837bcfecdcf04e130

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
    ]
